### PR TITLE
feat(consumer): manage consumption switches in group settings

### LINKED ISSUE #3990: [Studio][Feature] Expose the consumption switches of Apache consumer group settings
1. Please describe the feature you are requesting.

The consumer group settings editor (`GET/POST /api/groups/{name}/settings`, introduced by #2512) exposes only `retryQueueNums` and `retryMaxTimes`. The broker `SubscriptionGroupConfig` also carries the consumption switches that operators routinely need:

- `consumeEnable` — pause/resume consumption for a group without deleting it;
- `consumeMessageOrderly` — switch a group between concurrent and orderly consumption;
- `consumeBroadcastEnable` — allow broadcast-mode subscribers.

The classic dashboard (the previous generation in this repository, `frontend-new/src/components/consumer/ConsumerConfigItem.jsx` on the `master` branch) edits all of these fields via `/consumer/createOrUpdate.do`. In Studio today they can only be changed with external tooling such as `mqadmin updateSubGroup`.

2. Provide any additional detail on your proposed use case for this feature.

During an incident an operator needs to stop a misbehaving group from consuming further (disable `consumeEnable`), or flip a group to orderly consumption after introducing ordered delivery, directly from the dashboard. The existing settings endpoint already reads the effective broker config, updates every master broker, preserves unrelated fields, and writes an audit record; extending it with the three switches keeps that exact contract.

Cloud instances remain unsupported for this editor, matching the current `requireApacheInstance` scope of the settings endpoints. Omitted fields in the update payload should preserve the current broker values.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).

should-have. Workaround today is running `mqadmin updateSubGroup` manually against every broker.

4. Expected behavior / acceptance criteria

- `GET /api/groups/{name}/settings` returns `consumeEnable`, `consumeMessageOrderly` and `consumeBroadcastEnable` as read from the effective broker `SubscriptionGroupConfig`.
- `POST /api/groups/settings` accepts the three switches as optional booleans; an omitted switch preserves the current broker value (the endpoint's existing partial-update contract), and the update still targets every master broker while preserving unrelated fields and writing an audit record.
- The consumer detail modal's settings tab renders the three switches initialized from the GET response, and the save payload includes them.
- Cloud instances remain unsupported for this editor (unchanged `requireApacheInstance` gate).
All of the above are covered by the tests listed in the PR.

5. Related PR

- #3991 (`feat(consumer): manage consumption switches in group settings`) implements this request.

### PR DESCRIPTION
**Pull request by unbridled-41**
Fixes #3990.

## Source

- Parent project (the classic dashboard, previous generation of this repository, default branch `master`): [`frontend-new/src/components/consumer/ConsumerConfigItem.jsx`](https://github.com/apache/rocketmq-dashboard/blob/master/frontend-new/src/components/consumer/ConsumerConfigItem.jsx) exposes form switches for `consumeEnable`, `consumeMessageOrderly` and `consumeBroadcastEnable` and submits them through `/consumer/createOrUpdate.do` — the same broker `SubscriptionGroupConfig` API Studio's settings endpoint already drives.
- In-repo precedent: issue [#2512](https://github.com/apache/rocketmq-dashboard/issues/2512) introduced the Studio settings endpoint (read effective config → partial update on every master broker → audit). Its scope deliberately covered the two retry fields as the first slice; it never marked the remaining config fields as unsupported.
- Feature request filed for this gap: #3990.

## Current gap

On the base commit (36126024) the Studio settings editor carries only `retryQueueNums`/`retryMaxTimes`:

- `ConsumerGroupSettingsVO` / `UpdateConsumerGroupSettingsDTO` had exactly three fields; `RocketMQAdminClientImpl.updateConsumerGroupSettings` set only the two retry fields before `createAndUpdateSubscriptionGroupConfig`.
- The consumer detail modal's 配置 tab rendered two numeric inputs; the three switches were invisible.
- Verified against the working tree by grep (no `consumeEnable`/`consumeMessageOrderly`/`consumeBroadcastEnable` anywhere under `server/src/main/java` or `web/src`) and by the red tests below. Nothing in #2512, the design docs, or code comments marks the switches as intentionally unsupported — #2512's contract ("updates do not reset unrelated subscription-group fields") is in fact built to preserve them until they get an editor.

## Project fit

This extends an existing, Apache-gated editor along its own seam rather than adding a new surface: the endpoint already reads the effective broker config, updates every master broker, preserves unspecified fields, and writes an audit record — the switches ride the identical path. Cloud instances stay excluded behind the unchanged `requireApacheInstance` gate, matching how the retry fields behave today. In the UI, the switches join the existing 配置 tab of the consumer detail modal.

## Scope

Included:

- `GET /api/groups/{name}/settings` returns `consumeEnable` / `consumeMessageOrderly` / `consumeBroadcastEnable` read from the effective broker config.
- `POST /api/groups/settings` accepts the three switches as optional booleans; an omitted switch preserves the current broker value (the endpoint's existing partial-update contract).
- The consumer detail modal settings tab renders three `Switch` controls (启用消费 / 顺序消费 / 广播消费) initialized from the GET response; the audit record now includes the resulting switch values.

Not included: the classic dialog's `brokerId` / `whichBrokerWhenConsumeSlowly` broker-routing pair (advanced, error-prone, kept out for a minimal slice); any cloud-provider support; any database schema change (booleans live only in the broker config).

## Implementation

- `ConsumerGroupSettingsVO` +3 boolean fields; `UpdateConsumerGroupSettingsDTO` +3 optional `Boolean` fields (null = preserve).
- `AdminClient.updateConsumerGroupSettings` signature extended; `RocketMQAdminClientImpl` applies non-null switches per master broker before `createAndUpdateSubscriptionGroupConfig` and builds the returned VO from the final config state; the audit detail string lists the resulting values.
- `MetadataService` / `ConsumerGroupController` pass the values through; `MetadataService` continues to gate on `requireApacheInstance`.
- Web: `ConsumerGroupSettings` type +3 optional fields; the settings form gains three `Form.Item`/`Switch` rows following the modal's existing hardcoded-zh label style.

## Tests (actual commands and results)

New tests: `updateConsumerGroupSettingsAppliesConsumptionSwitches` and `getConsumerGroupSettingsReturnsConsumptionSwitches` (`RocketMQAdminClientImplTest`), `consumerGroupSettingsUpdateShouldForwardConsumptionSwitches` (`ConsumerGroupControllerTest`), `edits consumption switches from the detail modal settings tab` (`ConsumerPage.test.tsx`).

Red (implementation stashed, tests kept): server `mvn test-compile` → 9 compilation errors (`updateConsumerGroupSettings ... cannot be applied to given types` ×5, `cannot find symbol: method consumeEnable(boolean)` ×2, plus `consumeMessageOrderly`/`consumeBroadcastEnable`); web `npx vitest run src/pages/instance/__tests__/ConsumerPage.test.tsx -t "consumption switches"` → `TestingLibraryElementError: Unable to find role="switch" and name "启用消费"`.

Green:

- `mvn -ntp test -Dtest='RocketMQAdminClientImplTest,ConsumerGroupControllerTest,MetadataServiceTest'` → **Tests run: 100, Failures: 0, Errors: 0**.
- Full backend `mvn -ntp clean test` → **Tests run: 2038, Failures: 4** — the pristine baseline set of 36126024 (AuthCorsIntegrationTest ×2, AliyunInstanceProviderTest.getGroupProgressShouldMapLagRowsTest, load-fragile `OpenAiCompatibleLlmGatewayTest.successfulAndFailedStreamsEmitOneTerminalSequence`, which passes 9/9 in isolation). 2038 = 2035 baseline + 3 new tests; zero new failures.
- `npx vitest run src/pages/instance/__tests__/ConsumerPage.test.tsx` → **30 passed (30)**.
- Full web `npx vitest run` → **923 tests, 2 failed**, both in untouched files (ClientsPage search-reset, ConsumerPage health diagnostics), both passing in isolation (48/48 for the two files) — the documented load fragility of the full suite in this sandbox.
- `npx tsc -b` clean; `npx eslint` clean on the changed web files; `npm run build` succeeds.

## Compatibility & Risk

- Backward compatible: clients sending only the retry fields keep working — omitted switches preserve broker values (covered by the delegation test passing `null` switches). Additive only: no DB change, no new dependency, no license impact (only rocketmq client types already in use).
- Risk: operators can now pause consumption or flip orderly/broadcast from the UI — the same capability the classic dashboard exposes over the same admin API. The write path still updates every master broker and records an audit entry with the resulting values, and the editor remains Apache-only.
- Differences from the classic implementation: Studio keeps its read-validate-propagate-audit flow with per-broker config preservation instead of a blind form submit, and exposes only the three switches, not the broker-routing pair.

(head f2bd8631e43fb33ff584e8523fbbf78b7abfe296; verification details in the evidence comment below)

### CODE REVIEW

**Comment by unbridled-41** [comment]
## Verification evidence

- **CI**: head `f2bd8631e43fb33ff584e8523fbbf78b7abfe296` has 0 check runs and 0 statuses (combined state `pending`, no workflow run for this commit — verified via `commits/{sha}/check-runs`, `/status`, and `actions/runs?head_sha`). Upstream CI currently fails to start for all branches, so results below come from local execution.
- **Red (before the fix)**: with the implementation stashed and only tests applied — server `mvn test-compile`: 9 compilation errors (`updateConsumerGroupSettings ... cannot be applied to given types` ×5 in `RocketMQAdminClientImplTest`/`ConsumerGroupControllerTest`, `cannot find symbol: method consumeEnable(boolean)` ×2, `consumeMessageOrderly(boolean)`/`consumeBroadcastEnable(boolean)`); web `vitest run -t "consumption switches"`: `TestingLibraryElementError: Unable to find role="switch" and name "启用消费"`.
- **Module tests**: `mvn -ntp test -Dtest='RocketMQAdminClientImplTest,ConsumerGroupControllerTest,MetadataServiceTest'` → Tests run: 100, Failures: 0, Errors: 0. Web: `npx vitest run src/pages/instance/__tests__/ConsumerPage.test.tsx` → 30 passed (30).
- **Full suites + baseline**: backend `mvn -ntp clean test` → 2038 tests, 4 failures — byte-identical to the pristine baseline of 36126024 (AuthCorsIntegrationTest ×2, AliyunInstanceProviderTest.getGroupProgressShouldMapLagRowsTest, load-fragile OpenAiCompatibleLlmGatewayTest, 9/9 in isolation); 2038 = 2035 baseline + 3 new tests, zero new failures. Web `npx vitest run` → 923 tests, 2 failures (ClientsPage, ConsumerPage health diagnostics) — both in untouched files, both pass in isolation (the two files together 48/48), matching the documented load fragility of the full web suite in this sandbox.
- **Build**: `npm run build` succeeds (vite build ✓); `npx tsc -b` clean; `eslint` clean on the changed web files. Backend compiled as part of `mvn test`.
- **Diff self-check**: 11 files, +219/−16 — 6 server main files (VO/DTO/interface/impl/service/controller), 2 server test files, 3 web files (type + settings tab + test). No unrelated changes, no formatting-only churn, no generated/vendor edits.

**Review by RockteMQ-AI — COMMENTED** [review]
### Summary
This PR modifies 11 file(s) (410 lines) on `rocketmq-studio` ← `feat/consumer-group-consumption-switches`.

### Changed Files
```
server/src/main/java/org/apache/rocketmq/studio/instance/group/ConsumerGroupController.java
server/src/main/java/org/apache/rocketmq/studio/instance/group/ConsumerGroupSettingsVO.java
server/src/main/java/org/apache/rocketmq/studio/instance/group/UpdateConsumerGroupSettingsDTO.java
server/src/main/java/org/apache/rocketmq/studio/instance/topic/MetadataService.java
server/src/main/java/org/apache/rocketmq/studio/provider/apache/AdminClient.java
server/src/main/java/org/apache/rocketmq/studio/provider/apache/RocketMQAdminClientImpl.java
server/src/test/java/org/apache/rocketmq/studio/instance/group/ConsumerGroupControllerTest.java
server/src/test/java/org/apache/rocketmq/studio/provider/apache/RocketMQAdminClientImplTest.java
web/src/api/metadata.ts
web/src/pages/instance/__tests__/ConsumerPage.test.tsx
web/src/pages/instance/consumer.tsx
```

### Findings

- **[Info]** 3 test file(s) included.

- **[Warning]** API/protocol files detected (1). Ensure backward compatibility and coordinate with dependent projects.

---
*Automated review by github-manager-bot*
